/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces2;

import analizador.sintactico.backend.lexico.AnalizadorLexico;
import analizador.sintactico.backend.lexico.Token;
import com.mycompany.interfaces2.PantallaPrincipal;

/**
 *
 * @author odra
 */
public class Analizador extends javax.swing.JFrame {

    /**
     * Creates new form Analizador
     */
    protected String[] lineas;
    protected int iterador = 0;
    private AnalizadorLexico analizador;
    private String string;
    
    public Analizador(String texto) {

        initComponents();
        archivoVista.setText(texto);
        lineas = archivoVista.getText().split("\n");
        analizador = new AnalizadorLexico();
        string = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        archivoVista = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        lineaActual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        regresarbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        paneltokens = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        archivoVista.setColumns(20);
        archivoVista.setRows(5);
        jScrollPane1.setViewportView(archivoVista);

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lineaActual.setEditable(false);

        jLabel2.setText("Linea Actual");

        regresarbtn.setText("Regresar");
        regresarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarbtnActionPerformed(evt);
            }
        });

        exitbtn.setText("Salir");

        jScrollPane2.setViewportView(paneltokens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(lineaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(regresarbtn)
                                .addGap(18, 18, 18)
                                .addComponent(exitbtn)
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(28, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lineaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regresarbtn)
                            .addComponent(exitbtn)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (iterador < lineas.length) {
            lineaActual.setText(lineas[iterador]);
            analizador.setLineas(lineas[iterador]);
            analizador.setTope(false);
            analizador.setLinea(0);
            analizador.setPos(0);
            while (!analizador.isTope() && lineas[iterador]!=null && !lineas[iterador].equals("")) {
                Token token = analizador.analizarToken();
                token.setLinea(iterador+1);
                string+="POSICION: " + token.getPosicion() + "  PALABRA: " + token.getPalabra() + "  TIPO: " + token.getTipo() + "  LINEA: " + token.getLinea()+"\n";
                paneltokens.setText(string);
                System.out.println("posicion: " + token.getPosicion() + "  palabra: " + token.getPalabra() + "  tipo: " + token.getTipo() + "  linea: " + token.getLinea());
            }
            iterador++;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regresarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarbtnActionPerformed
        PantallaPrincipal pag = new PantallaPrincipal();
        pag.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarbtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea archivoVista;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lineaActual;
    private javax.swing.JTextPane paneltokens;
    private javax.swing.JButton regresarbtn;
    // End of variables declaration//GEN-END:variables
}
